import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import { io } from "socket.io-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const classes = `${inter.className} h-screen`;

  return (
    <html lang="en">
      <body className={classes}>{children}</body>
    </html>
  );
}
