apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
      version: 0.25.0
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    global:
      serverAddr: "https://vault.k8s.local"
    injector:
      enabled: true
      metrics:
        enabled: true
      agentImage:
        repository: hashicorp/vault
        tag: "1.13.1"
