---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 60m
  url: https://registry.groupein.local/repository/helm-gitlab
  secretRef:
    name: ca-cert