# apiVersion: v1
# kind: Secret
# metadata:
#   name: awx-postgres-configuration
#   namespace: awx-operator
# stringData:
#   host: dlkubedbpg01in.groupein.local
#   port: "5432"
#   database: awx
#   username: awx
#   password: "dV1TxqD4ELEJ0r2LA0z"
#   sslmode: prefer
#   type: unmanaged
# type: Opaque
