apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: monitoring
spec:
  storageClassName: storage-class-test
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
