apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.12.2
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    replicaCount: 2
    strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    image:
      repository: registry.groupein.local:9082/jetstack/cert-manager-controller
    webhook:
      image:
        repository: registry.groupein.local:9082/jetstack/cert-manager-webhook
    cainjector:
      image:
        repository: registry.groupein.local:9082/jetstack/cert-manager-cainjector
    startupapicheck:
      image:
        repository: registry.groupein.local:9082/jetstack/cert-manager-ctl
 