apiVersion: v1
kind: Secret
metadata:
  name: secret-vault-auth
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: cert-manager
secrets:
  - name: secret-vault-auth
